from flask import *
from flask_session import Session
import os,flightdefinitions,datetime,secrets,requests

app = Flask(__name__)
app.secret_key = str(secrets.token_urlsafe(16))
app.config['SESSION_TYPE'] = 'filesystem'
Session(app)

@app.route('/makeflightplan')
def makeflightplan():
    return render_template("makeflightplan.html")

@app.route('/')
def homepage():
    return render_template("index.html")

@app.route('/flightplan', methods = ['POST'])
def flightplan():
    if request.method == 'POST':
        from flask import g,session 
        deptapt = request.form['depticao'] 
        arrapt = request.form['arricao']
        aircraft = request.form['aircraft']
        pic = request.form['pic']
        callsign = request.form['callsign']
        rnav = request.form.get('rnav')
        usesid = request.form.get('usesid')
        usestar = request.form.get('usestar')
        rnav='Y' if rnav=='1' else rnav=='N'
        usesid='Y' if usesid=='1' else usesid=='N'
        usestar='Y' if usestar=='1' else usestar=='N'
        deptmetar=str(flightdefinitions.getmetar(str(deptapt)))
        arrmetar=str(flightdefinitions.getmetar(str(arrapt)))
        distance=((flightdefinitions.getdist(deptapt,arrapt)))
        distancenm=round((distance/1.852),2)
        kts = request.form['kts']
        time=round((float(distancenm)/float(kts)),2)
        time=str(time)
        alt = request.form['alt']
        myaltt=str('FL' + str(alt))
        rte = str(flightdefinitions.getFlightPath(deptapt, arrapt,myaltt,usesid, usestar, rnav,aircraft)[0])
        totfuel=str(flightdefinitions.getFlightPath(deptapt, arrapt,myaltt,usesid, usestar, rnav,aircraft)[3])
        rem = request.form['rem']
        t=((datetime.datetime.now())).strftime("%Y/%m/%d  %H:%M")
        finalplan=[ callsign,   #0
                    t,          #1
                    deptapt,    #2
                    deptmetar,  #3
                    arrapt,     #4
                    arrmetar,   #5
                    distancenm, #6
                    time,       #7
                    kts,        #8
                    alt,        #9
                    rte,        #10
                    totfuel,    #11
                    rem]        #12
        plan=finalplan
        atsfpl='''(FPL-'''+str(callsign)+'''-IS
        -'''+str(aircraft)+'''/M-SDE1E2E3FGHIJ2J3J4J5M1RWXY
        -'''+str(deptapt)+str((datetime.datetime.now()).strftime('%H%M'))+'''
        -N'''+str(kts)+'''F'''+str(alt)+str(((rte.replace(' ',' ')).replace('<b>','')).replace('\n',''))+'''
        -'''+str(arrapt)+str((((datetime.datetime.now())+(datetime.timedelta(hours=float(time))))).strftime('%H%M'))+'''
        -PBN/A1B1C1D1L1O1S2 DOF/'''+str(datetime.datetime.now().strftime('%y%m%d'))+''' REG/'''+str(callsign)+''' EET/'''+str(arrapt)+str(((datetime.datetime.now())+(datetime.timedelta(hours=float(time)))).strftime('%H%M'))+''' OPR/'''+str(''.join([c for c in callsign if c.isalpha()]))+''' PER/D C/'''+str(pic)+''' RMK/TCAS '''+str((rem.replace('\n','')))+' GENERATED BY EASYFLY FOR SIMULATION PURPOSES ONLY'
        data = {
    'callsign': str(callsign),
    'aircraftType': str(aircraft),
    'aircraftEquipment': 'SDE1E2E3FGHIJ2J3J4J5M1RWXY',
    'departure':str(deptapt),
    'depTime':str(str((datetime.datetime.now()).strftime('%H%M'))),
    'cruisingSpeed':str(str(kts)),
    'route':str(((rte.replace(' ',' ')).replace('<b>','')).replace('\n','')).replace('</B>','').replace('</b>',''),
    'destination':str(arrapt),
    'eet':str(str((((datetime.datetime.now())+(datetime.timedelta(hours=float(time))))).strftime('%H%M'))),
    'remarks':'''PBN/A1B1C1D1L1O1S2 DOF/'''+str(datetime.datetime.now().strftime('%y%m%d'))+''' REG/'''+str(callsign)+''' EET/'''+str(arrapt)+str(((datetime.datetime.now())+(datetime.timedelta(hours=float(time)))).strftime('%H%M'))+''' OPR/'''+str(''.join([c for c in callsign if c.isalpha()]))+''' PER/D C/'''+str(pic)+''' RMK/TCAS '''+str((rem.replace('\n','')))+''' FILED BY EASYFLY''',
    'endurance':str(((datetime.datetime.now())+(datetime.timedelta(hours=float(time)))).strftime('%H%M')),
    'pob':'1'
              }
        session['postdata']=data
        documentshtml='''
<html>
<head>
<title>'''+str(callsign)+''' : Flight Briefing // GENERATED BY EASYFLY</title>
<link rel="icon" type="image/png" href="https://webstockreview.net/images/airplane-clipart-logo-3.png"/>
    <style>
    @media screen {
        body {
          background: rgb(204,204,204);
          font-family:courier;
        }
        page {
          background: white;
          display: block;
          margin: 0 auto;
          margin-bottom: 0.5cm;
          box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);
        }
        page[size="A4"] {  
          width: 21cm; 
          height: 29.7cm; 
          padding:50px;
        }
        page[size="A4"][layout="landscape"] {
          width: 29.7cm;
          height: 21cm;  
        }
        page[size="A3"] {
          width: 29.7cm;
          height: 42cm;
        }
        page[size="A3"][layout="landscape"] {
          width: 42cm;
          height: 29.7cm;  
        }
        page[size="A5"] {
          width: 14.8cm;
          height: 21cm;
        }
        page[size="A5"][layout="landscape"] {
          width: 21cm;
          height: 14.8cm;  
        }
        .page-break {
              display: none;
        }
    }
    @media print {
          body, page {
            font-family:courier;
            margin: 0;
            box-shadow: 0;
            padding : 75px;
          }
          .noprint {display:none;};
          #noprint {display:none;}
          .page-break {
              page-break-before: always;
              display: block;
            }
    }
    </style>
</head>
<body onLoad="javascript:print()">
    <page size="A4" style="justify-content: center;">
    <br><br><br><br>
        <p align="center">
███████████████████████████████████████████
█▄─▄▄─██▀▄─██─▄▄▄▄█▄─█─▄█▄─▄▄─█▄─▄███▄─█─▄█
██─▄█▀██─▀─██▄▄▄▄─██▄─▄███─▄████─██▀██▄─▄██
▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▄▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▀▄▄▄▀▀
        </p><br><br><br><p align="center">PRE-FLIGHT BRIEFING</p><br><br><br>
        <pre align="center">
        '''+str(flightdefinitions.asciify(str(callsign)))+'''
        </pre>
        <br><br>
        <p align="center">['''+(str(callsign))+''']</p>
    </page>

    <div class="page-break"></div>

    <page size="A4">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>PILOT BRIEFING</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>    
        <table border="10px" align="center">
            <tr>
                <td>DATE AND TIME (LOCAL)</td>
                <td>'''+str(t)+'''</td>
            </tr>
            <tr>
                <td>FROM</td>
                <td title="Click to view plates"><a href="https://vau.aero/navdb/chart/'''+(str(deptapt))+'''.pdf" target="_blank">'''+(str(flightdefinitions.aptnamelatlon(deptapt)[0]))+'''</a></td>
            </tr>
            <tr>
                <td>TO</td>
                <td title="Click to view plates"><a href="https://vau.aero/navdb/chart/'''+(str(arrapt))+'''.pdf" target="_blank">'''+(str(flightdefinitions.aptnamelatlon(arrapt)[0]))+'''</a></td>
            </tr>
            <tr>
                <td>ROUTE</td>
                <td>'''+(str(rte))+'''</td>
            </tr>
            <tr>
                <td>ALTITUDE</td>
                <td>FL '''+(str(alt))+'''</td>
            </tr>
            <tr>
                <td>DISTANCE</td>
                <td>'''+(str(distance))+''' NAUTICAL MILES</td>
            </tr>
            <tr>
                <td>FLIGHT DURATION</td>
                <td>'''+(str(time))+''' HOURS</td>
            </tr>
            <tr>
                <td>'''+(str(deptapt))+'''</td>
                <td>'''+(str(deptmetar))+'''
                    <br><br>
                    '''+str(flightdefinitions.taf(str(deptapt).upper()))+'''
                    <br><br>
                    <pre>'''+str(flightdefinitions.metar(str(deptmetar)))+'''</pre>
                </td>
            </tr>
            <tr>
                <td>'''+(str(arrapt))+'''</td>
                <td>'''+(str(arrmetar))+'''
                    <br><br>
                    '''+str(flightdefinitions.taf(str(arrapt).upper()))+'''
                    <br><br>
                    <pre>'''+str(flightdefinitions.metar(str(arrmetar)))+'''</pre>
                </td>
            </tr>
        </table>
    </page>

    <div class="page-break"></div>

     <page size="A4">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>FPL MESSAGE FOR ATS (X.400 AMHS)</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>    
        <p align-"center">'''+(str(atsfpl.replace('\n','<br>')))+'''</p>
    </page>

    <div class="page-break"></div>

    <page style="width: 21cm; padding:50px;">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>NOTAMS</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>'''+str(flightdefinitions.getnotams(deptapt))+'''
    </page>

    <div class="page-break"></div>

    <page style="width: 21cm; padding:50px;">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>NOTAMS</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>'''+str(flightdefinitions.getnotams(arrapt))+'''
    </page>

    <div class="page-break"></div>

    <page size="A4">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>LOADSHEET</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br><pre align="center"> '''+(str(totfuel))+'''</pre>
    </page>

    <div class="page-break"></div>

    <page size="A4">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>FLIGHT ROUTE</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br><p><u>BRIEF</u></p><pre>'''+str(flightdefinitions.getFlightPath(deptapt, arrapt,myaltt,usesid, usestar, rnav,aircraft)[1])+'''</pre>
        <p><u>ROUTE</u></p>
        <br><pre align="center">'''+str(flightdefinitions.getFlightPath(deptapt, arrapt,myaltt,usesid, usestar, rnav,aircraft)[2])+'''</pre>
    </page>

    <div class="page-break"></div>

    <page size="A4">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>NOTES/REMARKS</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>    
            <div style="width:85%;border:1px solid #000;">RMK : '''+str(rem)+'''</div>
            <br>
            <p><u>NOTES</u></p>
    </page>

    <div class="page-break"></div>

    <page size="A4" class="noprint" id="noprint" style="width: 21cm; padding:150px;">
        <img src="https://webstockreview.net/images/airplane-clipart-logo-3.png" align="right" width=50px>
        <h3>DIGITAL PLATES</h3>
        <p>'''+(str(pic))+'''</p>
        <p>'''+str(t)+'''</p><h2 align="center">'''+(str(callsign))+'''</h2>
        <br><br>
        <p><u>'''+(str(deptapt))+'''</u></p>    
        <iframe width="85%" height="40%" src="https://vau.aero/navdb/chart/'''+(str(deptapt))+'''.pdf" align="center"></iframe>
        <br>
        <p><u>'''+(str(arrapt))+'''</u></p>    
        <iframe width="85%" height="40%" src="https://vau.aero/navdb/chart/'''+(str(arrapt))+'''.pdf" align="center"></iframe>
    </page>
</body>
</html>'''

        session['documentshtml']=documentshtml
        ivaofpl='''
[FLIGHTPLAN]
ID='''+str(callsign)+'''
RULES=I
FLIGHTTYPE=S
NUMBER=1
ACTYPE='''+str(aircraft)+'''
WAKECAT=
EQUIPMENT=SDE1E2E3FGHIJ2J3J4J5M1RWXY
TRANSPONDER=LB1D1
DEPICAO='''+str(deptapt)+'''
DEPTIME='''+str(str((datetime.datetime.now()).strftime('%H%M')))+'''
SPEEDTYPE=N
SPEED='''+str(str(kts))+'''
LEVELTYPE=F
LEVEL='''+str(alt)+'''
ROUTE='''+str(((rte.replace(' ',' ')).replace('<b>','')).replace('\n',''))+'''
DESTICAO='''+str(arrapt)+'''
EET='''+str(str((((datetime.datetime.now())+(datetime.timedelta(hours=float(time))))).strftime('%H%M')))+'''
ALTICAO=
ALTICAO2=
OTHER=PBN/A1B1C1D1L1O1S2 DOF/'''+str(datetime.datetime.now().strftime('%y%m%d'))+''' REG/'''+str(callsign)+''' EET/'''+str(arrapt)+str(((datetime.datetime.now())+(datetime.timedelta(hours=float(time)))).strftime('%H%M'))+''' OPR/'''+str(''.join([c for c in callsign if c.isalpha()]))+''' PER/D C/'''+str(pic)+''' RMK/TCAS '''+str((rem.replace('\n','')))+''' FILED BY EASYFLY
ENDURANCE=
POB=365'''
    


        session['ivaofpl']=ivaofpl
        return str('''<html>
    <title>'''+str(plan[0])+'''</title>
        <!-- Material Design Lite -->
        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-deep_orange.min.css" />
        <!-- Material Design icon font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="icon" type="image/png" href="https://webstockreview.net/images/airplane-clipart-logo-3.png"/>
        <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <style>
    html { overflow-y: scroll; overflow-x:hidden; scroll-behavior: smooth;}
    body {position: absolute; }
    #view-source {
    position: fixed;
    display: block;
    right: 0;
    bottom: 0;
    margin-right: 40px;
    margin-bottom: 40px;
    z-index: 900;
    }
    .demo-card-wide.mdl-card {
      width: 85%;
    }
    .demo-card-wide-1.mdl-card {
      width: 100%;
    }

    .demo-card-wide-1 > .mdl-card__menu {
      color: #fff;
    }

    .mdl-layout {
      align-items: center;
      justify-content: center;
    }
table {
    table-layout: fixed;
}
td {
    overflow:hidden;
}
    @media print
    {
    #view-source {display:none;}
    #liawetmat {display:none;}
    #liprnopo {display:none;}
    #lliawetmat {display:none;}
    #nlieawetmat {display:none;}
    #m80 {display:none;}
    #readys {display:none;}
    #uniqwo {display:none;}
    #unreadys {display:none;}
    #noprrrrr {display:none;}
    .demo-card-wide-1 {display:none;}
    .noprint {display:none;}
    .mdl-button-1 {display:none;}
    }
    #view-source {
        position: fixed;
        display: block;
        right: 0;
        bottom: 0;
        margin-right: 40px;
        margin-bottom: 40px;
        z-index: 900;
        }
    @media screen
    {
    ...
    }
    //.iframe-container {
    //    overflow-x:scroll;
    //    overflow-y: scroll;
    //    padding-top: 56.25%;
    //    position: relative;
    //}
    //.iframe-container iframe {
    //   border: 0;
    //   height: 100%;
    //   left: 0;
    //   position: absolute;
    //   top: 0;
    //   width: 100%;
    //}
    </style>
    </head>
    <body style="background-image:url('https://wallpaperaccess.com/full/445636.jpg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed;">
    <br>
    <div class="mdl-layout">
    <div class="demo-card-wide mdl-card mdl-shadow--2dp through mdl-shadow--16dp" align="center">
    <div class="table-responsive mdl-shadow--4dp">
    <table class="mdl-data-table mdl-js-data-table" align="center">
    <tbody>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">CALLSIGN</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str((plan[0]))+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">SCHEDULED TIME OF DEPARTURE</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(t)+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">DEPARTURE AIRPORT</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(flightdefinitions.aptnamelatlon(plan[2])[0])+'''</button></a></td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">METAR AT DEPARTURE AIRPORT</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(plan[3])+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">ARRIVAL AIRPORT</td>
    <td class="mdl-data-table__cell--non-numeric" id="arraptt">'''+str(flightdefinitions.aptnamelatlon(plan[4])[0])+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">METAR AT ARRIVAL AIRPORT</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(plan[5])+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">DISTANCE</td>
    <td class="mdl-data-table__cell--non-numeric">'''+f'{plan[6]} NAUTICAL MILES'+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">FLIGHT DURATION</td>
    <td class="mdl-data-table__cell--non-numeric">'''+f'{plan[7]} HOURS'+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">CRUISE SPEED</td>
    <td class="mdl-data-table__cell--non-numeric">'''+f'{plan[8]} KNOTS'+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">CRUISE ALTITUDE</td>
    <td class="mdl-data-table__cell--non-numeric">'''+f'FL {plan[9]}'+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">ROUTE</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(plan[10])+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric">REMARKS</td>
    <td class="mdl-data-table__cell--non-numeric">'''+str(plan[12])+'''</td>
    </tr>
    <tr>
    <td class="mdl-data-table__cell--non-numeric"><pre><a href="/ivaofpl" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--primary mdl-color-text--accent-contrast noprint" target="_blank">DOWNLOAD AS IVAO FPL FORMAT</a>   <a href="/prefile" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--primary mdl-color-text--accent-contrast noprint" target="_blank">PREFILE ON IVAO</a></pre></td>
    </tr>
    </tbody>
    </table>
    </div>
    </div>
     <a href="/documents" target="_blank" id="view-source" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--primary mdl-color-text--accent-contrast noprint" style="color:white;">View and Print Documents</a>''')

@app.route('/documents')
def documents():
    from flask import g,session
    return session.get('documentshtml')

@app.route('/ivaofpl')
def ivaofpl():
    from flask import g,session
    with open('IVAO.fpl','w') as f:
        f.write(session.get('ivaofpl'))
    return send_file("IVAO.fpl", as_attachment=True)

@app.route('/prefile')
def prefile():
    from flask import g,session
    with requests.Session() as s:
        url = 'https://fpl.ivao.aero/fp/save'
        r = s.post(url, data=session.get('postdata'))
    return redirect('https://fpl.ivao.aero/')


if __name__ == '__main__':
    app.run(debug = False)